#!/usr/bin/bash

config_file="${PSVR2_CONFIG:-$HOME/.config/psvr2-linux/settings.env}"
if [[ -r "$config_file" ]]; then
    # shellcheck disable=SC1090
    source "$config_file"
fi

PSVR2_RENDER_SCALE="${PSVR2_RENDER_SCALE:-170}"
PSVR2_REFRESH_RATE="${PSVR2_REFRESH_RATE:-120}"
PSVR2_SPECTATOR_ENABLE="${PSVR2_SPECTATOR_ENABLE:-1}"
PSVR2_SETUP_ROOT="${PSVR2_SETUP_ROOT:-$HOME/.local/share/psvr2-setup}"
PSVR2_CHAPERONE_ENABLE="${PSVR2_CHAPERONE_ENABLE:-1}"
PSVR2_CHAPERONE_BINARY="${PSVR2_CHAPERONE_BINARY:-$PSVR2_SETUP_ROOT/xr-chaperone/xr-chaperone.AppImage}"
PSVR2_CHAPERONE_SERVICE_ARGS="${PSVR2_CHAPERONE_SERVICE_ARGS:--s}"
PSVR2_LINK_STABILITY_CHECKS="${PSVR2_LINK_STABILITY_CHECKS:-4}"
PSVR2_LINK_DISCONNECT_CHECKS="${PSVR2_LINK_DISCONNECT_CHECKS:-2}"
PSVR2_LINK_STABILITY_INTERVAL_SECONDS="${PSVR2_LINK_STABILITY_INTERVAL_SECONDS:-1}"
PSVR2_STARTUP_RETRY_BASE_SECONDS="${PSVR2_STARTUP_RETRY_BASE_SECONDS:-12}"
PSVR2_STARTUP_RETRY_MAX_SECONDS="${PSVR2_STARTUP_RETRY_MAX_SECONDS:-120}"
PSVR2_STARTUP_RETRY_ATTEMPTS="${PSVR2_STARTUP_RETRY_ATTEMPTS:-3}"
PSVR2_OPENVR_FAILURE_STREAK_THRESHOLD="${PSVR2_OPENVR_FAILURE_STREAK_THRESHOLD:-2}"
PSVR2_OPENVR_FAILURE_RECOVERY_SECONDS="${PSVR2_OPENVR_FAILURE_RECOVERY_SECONDS:-90}"
PSVR2_RUNTIME_FAILURE_STREAK_THRESHOLD="${PSVR2_RUNTIME_FAILURE_STREAK_THRESHOLD:-$PSVR2_OPENVR_FAILURE_STREAK_THRESHOLD}"
PSVR2_RUNTIME_FAILURE_RECOVERY_SECONDS="${PSVR2_RUNTIME_FAILURE_RECOVERY_SECONDS:-$PSVR2_OPENVR_FAILURE_RECOVERY_SECONDS}"
PSVR2_RUNTIME_RETRY_COOLDOWN_SECONDS="${PSVR2_RUNTIME_RETRY_COOLDOWN_SECONDS:-$PSVR2_RUNTIME_FAILURE_RECOVERY_SECONDS}"
PSVR2_DISCONNECT_CONTROLLERS="${PSVR2_DISCONNECT_CONTROLLERS:-1}"
STEAM_ROOT="${STEAM_ROOT:-$HOME/.local/share/Steam}"
ENVISION_PROFILE_ROOT="${ENVISION_PROFILE_ROOT:-$HOME/.local/share/envision/psvr2-toolkit-monado}"
MONADO_PREFIX="${MONADO_PREFIX:-$HOME/.local/share/envision/prefixes/psvr2-toolkit-monado}"
PSVR2_ENABLE_STEAMVR_BRIDGE="${PSVR2_ENABLE_STEAMVR_BRIDGE:-0}"
PSVR2_ENABLE_STEAMVR_LH="${PSVR2_ENABLE_STEAMVR_LH:-0}"
AMD_VULKAN_DEVICE="${AMD_VULKAN_DEVICE:-}"
DGPU_PCI_ADDRESS="${DGPU_PCI_ADDRESS:-}"
VR_AUDIO_SINK="${VR_AUDIO_SINK:-}"
VR_AUDIO_SOURCE="${VR_AUDIO_SOURCE:-}"
CONTROLLER_LEFT_MAC="${CONTROLLER_LEFT_MAC:-}"
CONTROLLER_RIGHT_MAC="${CONTROLLER_RIGHT_MAC:-}"
STEAM_COMMAND="${STEAM_COMMAND:-steam}"

export PSVR2_RENDER_SCALE PSVR2_REFRESH_RATE PSVR2_SPECTATOR_ENABLE
export PSVR2_CHAPERONE_ENABLE PSVR2_CHAPERONE_BINARY PSVR2_CHAPERONE_SERVICE_ARGS
export PSVR2_LINK_STABILITY_CHECKS PSVR2_LINK_DISCONNECT_CHECKS
export PSVR2_LINK_STABILITY_INTERVAL_SECONDS
export PSVR2_STARTUP_RETRY_BASE_SECONDS PSVR2_STARTUP_RETRY_MAX_SECONDS PSVR2_STARTUP_RETRY_ATTEMPTS
export PSVR2_OPENVR_FAILURE_STREAK_THRESHOLD PSVR2_OPENVR_FAILURE_RECOVERY_SECONDS
export PSVR2_RUNTIME_FAILURE_STREAK_THRESHOLD PSVR2_RUNTIME_FAILURE_RECOVERY_SECONDS PSVR2_RUNTIME_RETRY_COOLDOWN_SECONDS
export PSVR2_DISCONNECT_CONTROLLERS
export PSVR2_ENABLE_STEAMVR_BRIDGE PSVR2_ENABLE_STEAMVR_LH
export STEAM_ROOT ENVISION_PROFILE_ROOT
export MONADO_PREFIX PSVR2_SETUP_ROOT AMD_VULKAN_DEVICE DGPU_PCI_ADDRESS
